### ISSUE TITLE
July 27th Playground bug hunt issues

### ISSUE THREAD

**Issue by alse** [onflow/flow-playground#290]
## Issues:

- [x] onflow/cadence#285
- [x] onflow/cadence#286
- [x] onflow/cadence#287
- [x] onflow/cadence#296
- [x] onflow/cadence#297
- [x] onflow/cadence#292
- [x] onflow/cadence#295
- [x] onflow/cadence#300
- [x] onflow/cadence#294 
- [x] onflow/cadence#299
- [x] onflow/cadence#298

- [ ] https://github.com/onflow/cadence-tools/issues/36

### Contract examples
https://open-cadence.onflow.org

- [x] "Create a Topshot Set" contract: Accounts with non-relevant contracts not distinguished besides having boilerplate HelloWorld contract. https://play.onflow.org/15c1e86e-010c-4a7c-bcfd-98a1bddc36a7?type=tx&id=9e42f1aa-3f25-4ffc-87f0-b9d109e1d851&storage=none (won't-fix, will not apply to the new playground)
- [x] Contracts have errors upon opening  (won't-fix, will not apply to the new playground)
- [x] General UX: Accounts not ordered in the order you need to deploy contracts (won't-fix, will not apply to the new playground)
- [x] onflow/cadence#301

## Duplicates:
Verify these are complete after linked issues are resolved

- [x] I see some characters being deleted after deploying, then erroring. For example, `pub var … -> pub va … -> unrecognized syntax ‘va’` (Covered by https://github.com/onflow/flow-playground/issues/287 )
- [x] The issues from the past report seems to be persisting. (update: it's likely that onflow/cadence#285 onflow/cadence#286 onflow/cadence#287 covers these issues)
- [x] Need to refresh page after deploying contracts (related to https://github.com/onflow/flow-playground/issues/286 ?)
- [x] Account storage doesn’t show deployed contracts (is it supposed to?) (same as onflow/cadence#292 ?)
- [x] Adding a new member function to a resource in a contract, and then redeploying the contract: The new member is not available in code-completions in transactions and scripts without a hard reload of the browser. (related to https://github.com/onflow/flow-playground/issues/286 ?)
- [x] 08 MarketPlace Compose tutorial: After deploying ExampleMarketplace to 0x03, this script CreateSale still does not recognize the contract when importing (Works after page refresh, this should be covered by https://github.com/onflow/flow-playground/issues/286)

## Can't reproduce:
- [x] Contract examples: Can’t find any declarations between accounts/ templates → Can’t deploy other contracts or send transaction templates (could not reproduce these errors)
- [x] Deployment result section resizes to default when switching accounts

## Complete:
- [x] Tutorial 03 Resources: Initial template has incorrect import. Contract needs to be imported from 0x01 not 0x02. The resource does not show up in the account storage however
- [x] Tutorial 04 Capabilities: Transaction works as expected when following the tutorial documentation however, the contract address needed to be changed from 0x02 to 0x01
- [x]  Tutorial 04 Capabilities: Documentation and snippet do not align
