### ISSUE TITLE
[Epic] Replace Playground V1 with V2 to improve Cadence Prototyping experience

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#565]
Branch off current production to create a V1 codebase, we can use it for reference and host at v1.play.flow.com.
Then promote (merge) beta to production, so that play.flow.com will be the beta (v2) code base.

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/database-migrator/issues/2
- [ ] https://github.com/onflow/flow-playground-api/issues/223
- [ ] https://github.com/onflow/flow-playground/issues/575
- [ ] https://github.com/onflow/flow-playground/issues/560
- [ ] https://github.com/onflow/flow-playground/issues/571
- [ ] https://github.com/onflow/flow-playground-api/issues/219
- [ ] https://github.com/onflow/flow-playground-api/issues/209
- [ ] https://github.com/dapperlabs/flow-playground-api/pull/109
- [ ] https://github.com/onflow/flow-playground-api/issues/230
```

**Comment by DylanTinianov** [comment]
Released v2
