### ISSUE TITLE
Update Playground to support Cadence 1.0

### ISSUE THREAD

**Issue by gregsantos** [onflow/flow-playground#760]
Once playground api uses the new emulator that supports 1.0 (Im not sure if we can do this now)
After which, we can update all the reference templates. Then update all the urls to reference templates. This might effect cadence cookbook
Users: old projects will fail to deploy and force users to fix their projects.

```[tasklist]
### Tasks
- [x] Create "cadence-1.0" branches for playground-api and flow-playground repos to support Cadence 1.0
- [x] flow-playground update to new dependencies that support Cadence 1.0
- [x] playground-api update to new dependencies that support Cadence 1.0
- [x] Deploy new instance of flow-playground to vercel
- [x] Deploy new playground-api to new deployment environment.
- [ ] https://github.com/onflow/flow-playground/issues/778
```
